app:
  access_token_duration: 3600
  refresh_token_duration: 5000
  jwt_secret_key: Im5hbWUiOiIwMTkwMTkwMTkwMUBtYWlsaW5hdG9yLmNvbSIsInRva2VuX3R5cGUiOiJhY2Nlc3MifQ
  port: 8080
postgres:
  host: postgres
  port: 5432
  user: minishop
  password: supersecretpasswd
  db_name: minishop
  timezone: Asia/Dhaka
  ssl_mode: disable
