version: '3.8'

services:
  postgres:
    image: postgres:15 # Use the desired PostgreSQL version
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: minishop
      POSTGRES_PASSWORD: supersecretpasswd
      POSTGRES_DB: minishop
    ports:
      - "5432:5432" # Maps port 5432 of the container to port 5432 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data to avoid loss on container restart

volumes:
  postgres_data:
